// ==UserScript==
// @name                Use My Fonts
// @name:en-US          Use My Fonts
// @name:zh-CN          使用我的字体
// @description         Use my custom fonts on the pages
// @description:en-US   Use my custom fonts on the pages
// @description:zh-CN   在页面上使用我的自定义字体
// @namespace           use-my-fonts
// @version             2025.08.06
// @author              Akatsuki Rui
// @license             MIT License
// @grant               GM_addStyle
// @run-at              document-start
// @match               *://*/*
// ==/UserScript==

"use strict";

const css = String.raw;

// FONT_CSS is generated by fonts.scss
const FONT_CSS = `
@charset "UTF-8";
@font-face { font-family: "Arial"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Arial"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Arial"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Arial"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Arial"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Arial"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Arial"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Arial"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Arial"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Arial"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Arial"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Arial"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Helvetica"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Helvetica"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Helvetica"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Helvetica"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Helvetica"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Helvetica"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Helvetica"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Lucida Grande"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Lucida Grande"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Lucida Grande"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Lucida Grande"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Lucida Grande"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Lucida Grande"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Lucida Grande"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Lucida Sans Unicode"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Open Sans"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Open Sans"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Open Sans"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Open Sans"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Open Sans"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Open Sans"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Open Sans"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Segoe UI"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Segoe UI"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Segoe UI"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Segoe UI"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Segoe UI"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Segoe UI"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Segoe UI"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Tahoma"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Tahoma"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Tahoma"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Tahoma"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Tahoma"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Tahoma"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Tahoma"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Verdana"; font-weight: 100; src: local("Roboto Thin"); }
@font-face { font-family: "Verdana"; font-weight: 300; src: local("Roboto Light"); }
@font-face { font-family: "Verdana"; font-weight: 400; src: local("Roboto Regular"); }
@font-face { font-family: "Verdana"; font-weight: 500; src: local("Roboto Medium"); }
@font-face { font-family: "Verdana"; font-weight: 700; src: local("Roboto Bold"); }
@font-face { font-family: "Verdana"; font-weight: 900; src: local("Roboto Black"); }
@font-face { font-family: "Verdana"; font-weight: 100; font-style: italic; src: local("Roboto Thin Italic"); }
@font-face { font-family: "Verdana"; font-weight: 300; font-style: italic; src: local("Roboto Light Italic"); }
@font-face { font-family: "Verdana"; font-weight: 400; font-style: italic; src: local("Roboto Italic"); }
@font-face { font-family: "Verdana"; font-weight: 500; font-style: italic; src: local("Roboto Medium Italic"); }
@font-face { font-family: "Verdana"; font-weight: 700; font-style: italic; src: local("Roboto Bold Italic"); }
@font-face { font-family: "Verdana"; font-weight: 900; font-style: italic; src: local("Roboto Black Italic"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "Microsoft YaHei UI"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "Microsoft YaHei"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "微软雅黑"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "微软雅黑"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "微软雅黑"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "微软雅黑"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "微软雅黑"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "微软雅黑"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "NSimsun"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "NSimsun"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "NSimsun"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "NSimsun"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "NSimsun"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "NSimsun"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "新宋体"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "新宋体"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "新宋体"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "新宋体"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "新宋体"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "新宋体"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "Simsun"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "Simsun"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "Simsun"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "Simsun"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "Simsun"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "Simsun"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "宋体"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "宋体"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "宋体"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "宋体"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "宋体"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "宋体"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "Simhei"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "Simhei"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "Simhei"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "Simhei"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "Simhei"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "Simhei"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "黑体"; font-weight: 100; src: local("Noto Sans CJK SC Thin"); }
@font-face { font-family: "黑体"; font-weight: 300; src: local("Noto Sans CJK SC Light"); }
@font-face { font-family: "黑体"; font-weight: 400; src: local("Noto Sans CJK SC Regular"); }
@font-face { font-family: "黑体"; font-weight: 500; src: local("Noto Sans CJK SC Medium"); }
@font-face { font-family: "黑体"; font-weight: 700; src: local("Noto Sans CJK SC Bold"); }
@font-face { font-family: "黑体"; font-weight: 900; src: local("Noto Sans CJK SC Black"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 100; src: local("Noto Sans CJK TC Thin"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 300; src: local("Noto Sans CJK TC Light"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 400; src: local("Noto Sans CJK TC Regular"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 500; src: local("Noto Sans CJK TC Medium"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 700; src: local("Noto Sans CJK TC Bold"); }
@font-face { font-family: "Microsoft Jhenghei"; font-weight: 900; src: local("Noto Sans CJK TC Black"); }
@font-face { font-family: "微軟正黑體"; font-weight: 100; src: local("Noto Sans CJK TC Thin"); }
@font-face { font-family: "微軟正黑體"; font-weight: 300; src: local("Noto Sans CJK TC Light"); }
@font-face { font-family: "微軟正黑體"; font-weight: 400; src: local("Noto Sans CJK TC Regular"); }
@font-face { font-family: "微軟正黑體"; font-weight: 500; src: local("Noto Sans CJK TC Medium"); }
@font-face { font-family: "微軟正黑體"; font-weight: 700; src: local("Noto Sans CJK TC Bold"); }
@font-face { font-family: "微軟正黑體"; font-weight: 900; src: local("Noto Sans CJK TC Black"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "ヒラギノ角ゴ Pro W3"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "Hiragino Kaku Gothic Pro"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "ＭＳ ゴシック"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "MS Gothic"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "MS Gothic"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "MS Gothic"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "MS Gothic"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "MS Gothic"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "MS Gothic"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "ＭＳ Ｐゴシック"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "MS PGothic"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "MS PGothic"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "MS PGothic"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "MS PGothic"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "MS PGothic"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "MS PGothic"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "メイリオ"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "メイリオ"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "メイリオ"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "メイリオ"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "メイリオ"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "メイリオ"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "Meiryo"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "Meiryo"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "Meiryo"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "Meiryo"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "Meiryo"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "Meiryo"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "Osaka"; font-weight: 100; src: local("Noto Sans CJK JP Thin"); }
@font-face { font-family: "Osaka"; font-weight: 300; src: local("Noto Sans CJK JP Light"); }
@font-face { font-family: "Osaka"; font-weight: 400; src: local("Noto Sans CJK JP Regular"); }
@font-face { font-family: "Osaka"; font-weight: 500; src: local("Noto Sans CJK JP Medium"); }
@font-face { font-family: "Osaka"; font-weight: 700; src: local("Noto Sans CJK JP Bold"); }
@font-face { font-family: "Osaka"; font-weight: 900; src: local("Noto Sans CJK JP Black"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 100; src: local("Noto Sans CJK KR Thin"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 300; src: local("Noto Sans CJK KR Light"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 400; src: local("Noto Sans CJK KR Regular"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 500; src: local("Noto Sans CJK KR Medium"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 700; src: local("Noto Sans CJK KR Bold"); }
@font-face { font-family: "Malgun Gothic"; font-weight: 900; src: local("Noto Sans CJK KR Black"); }
@font-face { font-family: "맑은 고딕"; font-weight: 100; src: local("Noto Sans CJK KR Thin"); }
@font-face { font-family: "맑은 고딕"; font-weight: 300; src: local("Noto Sans CJK KR Light"); }
@font-face { font-family: "맑은 고딕"; font-weight: 400; src: local("Noto Sans CJK KR Regular"); }
@font-face { font-family: "맑은 고딕"; font-weight: 500; src: local("Noto Sans CJK KR Medium"); }
@font-face { font-family: "맑은 고딕"; font-weight: 700; src: local("Noto Sans CJK KR Bold"); }
@font-face { font-family: "맑은 고딕"; font-weight: 900; src: local("Noto Sans CJK KR Black"); }
@font-face { font-family: "Consolas"; font-weight: 200; src: local("Cascadia Code ExtraLight"); }
@font-face { font-family: "Consolas"; font-weight: 300; src: local("Cascadia Code Light"); }
@font-face { font-family: "Consolas"; font-weight: 350; src: local("Cascadia Code SemiLight"); }
@font-face { font-family: "Consolas"; font-weight: 400; src: local("Cascadia Code Regular"); }
@font-face { font-family: "Consolas"; font-weight: 600; src: local("Cascadia Code SemiBold"); }
@font-face { font-family: "Consolas"; font-weight: 700; src: local("Cascadia Code Bold"); }
@font-face { font-family: "Consolas"; font-weight: 200; font-style: italic; src: local("Cascadia Code ExtraLight Italic"); }
@font-face { font-family: "Consolas"; font-weight: 300; font-style: italic; src: local("Cascadia Code Light Italic"); }
@font-face { font-family: "Consolas"; font-weight: 350; font-style: italic; src: local("Cascadia Code SemiLight Italic"); }
@font-face { font-family: "Consolas"; font-weight: 400; font-style: italic; src: local("Cascadia Code Regular Italic"); }
@font-face { font-family: "Consolas"; font-weight: 600; font-style: italic; src: local("Cascadia Code SemiBold Italic"); }
@font-face { font-family: "Consolas"; font-weight: 700; font-style: italic; src: local("Cascadia Code Bold Italic"); }
`;

GM_addStyle(FONT_CSS.trim());
